"""PkgForge sidecar API package (F2.2: split from core/api_server.py)."""
from core.api import (
    handlers_pipeline,
    handlers_queue,
    handlers_repo,
    handlers_security,
    handlers_system,
    handlers_tools,
    http,
    protocol,
    registry,
    transport,
)
from core.api.handlers_pipeline import (
    handle_history_clear,
    handle_history_restore,
    handle_history_rollback,
    handle_history_uninstall,
    handle_pipeline_approve,
    handle_pipeline_cancel,
    handle_pipeline_dismiss,
    handle_pipeline_start,
)
from core.api.handlers_queue import (
    _active_pipelines,
    _ensure_scheduler,
    _get_queue_store,
    _make_pipeline,
    _persist_clear,
    _persist_item,
    _persist_remove,
    _profile_name,
    _queue_dispatch,
    _queue_items,
    _queue_lock,
    _queue_running,
    _queue_seq,
    _queue_store,
    _queue_store_lock,
    _schedule_state,
    _scheduler_started,
    _scheduler_tick,
    _set_item,
    handle_profile_create,
    handle_profile_delete,
    handle_profile_switch,
    handle_queue_add,
    handle_queue_cancel,
    handle_queue_clear,
    handle_queue_list,
    handle_queue_priority,
    handle_queue_remove,
    handle_queue_start,
    handle_schedule_get,
    handle_schedule_run,
    handle_schedule_set,
    handle_schedule_timer_install,
    handle_sync_config,
    handle_sync_export,
    handle_sync_import,
    handle_sync_pull,
    handle_sync_push,
    restore_queue,
)
from core.api.handlers_repo import (
    _AUR_NAME_RE,
    _validate_aur_name,
    handle_aur_build,
    handle_aur_info,
    handle_aur_search,
    handle_compare_diff,
    handle_plugin_install,
    handle_plugin_uninstall,
    handle_plugin_update,
)
from core.api.handlers_security import (
    handle_security_cve_scan,
    handle_security_keys,
    handle_security_provenance,
    handle_security_provenance_create,
    handle_security_quality,
    handle_security_sbom,
    handle_security_sign,
    handle_security_sigstore_status,
    handle_security_verify,
)
from core.api.handlers_system import (
    handle_delta_disable,
    handle_delta_enable,
    handle_delta_status,
    handle_export_appimage_to_deb,
    handle_export_flatpak_list,
    handle_export_flatpak_to_deb,
    handle_export_oci,
    handle_graph_build,
    handle_source_generate,
    handle_system_benchmark,
    handle_system_cross_check,
    handle_system_install_pkg,
    handle_system_open_path,
    handle_system_snapshot_install,
    handle_system_snapshot_remove,
    handle_system_snapshot_status,
    handle_system_verify_rollback,
)
from core.api.handlers_tools import (
    handle_dbus_set_policy,
    handle_dbus_start,
    handle_fleet_status,
    handle_install_rehearse,
    handle_tools_abi_check,
    handle_tools_attest,
    handle_tools_audit,
    handle_tools_publish,
    handle_tools_rpm_to_deb,
    handle_tools_scan_image,
    handle_tools_snapshot_install,
    handle_tools_snapshot_remove,
    handle_tools_snapshot_status,
)
from core.api.http import (
    _HTTP_MAX_BODY,
    _HTTP_RATE_LIMIT,
    _READ_METHODS,
    _http_rate,
    _http_validate_bind,
    _make_http_handler,
    _rate_limited,
    _resolve_client_ip,
    build_openapi_schema,
    serve_http,
)
from core.api.protocol import (
    _MAIN_THREAD_METHODS,
    _dispatch,
    _dispatch_blocking,
    _route_request,
    serve,
)
from core.api.registry import METHODS
from core.api.transport import (
    _ensure_qapp,
    _error,
    _event,
    _http_mode,
    _pipeline,
    _require_pkg_file,
    _result,
    _run_security_thread,
    _run_thread,
    _send,
    _sse_history,
    _sse_lock,
    _sse_publish,
    _sse_subscribe,
    _sse_subscribers,
    _sse_unsubscribe,
    _write_lock,
)
from core.http_api.meta import (
    handle_app_doctor,
    handle_app_version,
    handle_policy_evaluate,
    handle_policy_get,
    handle_policy_set,
    handle_settings_get,
    handle_settings_set,
    handle_stats_wrapped,
    handle_system_health,
    handle_tools_status,
)
from core.http_api.read import (
    handle_dbus_status,
    handle_history_list,
    handle_plugin_audit,
    handle_plugin_available,
    handle_plugin_list,
    handle_profile_current,
    handle_profile_list,
)

__all__ = ['METHODS', '_AUR_NAME_RE', '_HTTP_MAX_BODY', '_HTTP_RATE_LIMIT', '_MAIN_THREAD_METHODS', '_READ_METHODS', '_active_pipelines', '_dispatch', '_dispatch_blocking', '_ensure_qapp', '_ensure_scheduler', '_error', '_event', '_get_queue_store', '_http_mode', '_http_rate', '_http_validate_bind', '_make_http_handler', '_make_pipeline', '_persist_clear', '_persist_item', '_persist_remove', '_pipeline', '_profile_name', '_queue_dispatch', '_queue_items', '_queue_lock', '_queue_running', '_queue_seq', '_queue_store', '_queue_store_lock', '_rate_limited', '_require_pkg_file', '_resolve_client_ip', '_result', '_route_request', '_run_security_thread', '_run_thread', '_schedule_state', '_scheduler_started', '_scheduler_tick', '_send', '_set_item', '_sse_history', '_sse_lock', '_sse_publish', '_sse_subscribe', '_sse_subscribers', '_sse_unsubscribe', '_validate_aur_name', '_write_lock', 'build_openapi_schema', 'handle_aur_build', 'handle_aur_info', 'handle_aur_search', 'handle_compare_diff', 'handle_dbus_set_policy', 'handle_dbus_start', 'handle_delta_disable', 'handle_delta_enable', 'handle_delta_status', 'handle_export_appimage_to_deb', 'handle_export_flatpak_list', 'handle_export_flatpak_to_deb', 'handle_export_oci', 'handle_fleet_status', 'handle_graph_build', 'handle_history_clear', 'handle_history_restore', 'handle_history_rollback', 'handle_history_uninstall', 'handle_install_rehearse', 'handle_pipeline_approve', 'handle_pipeline_cancel', 'handle_pipeline_dismiss', 'handle_pipeline_start', 'handle_plugin_install', 'handle_plugin_uninstall', 'handle_plugin_update', 'handle_profile_create', 'handle_profile_delete', 'handle_profile_switch', 'handle_queue_add', 'handle_queue_cancel', 'handle_queue_clear', 'handle_queue_list', 'handle_queue_priority', 'handle_queue_remove', 'handle_queue_start', 'handle_schedule_get', 'handle_schedule_run', 'handle_schedule_set', 'handle_schedule_timer_install', 'handle_security_cve_scan', 'handle_security_keys', 'handle_security_provenance', 'handle_security_provenance_create', 'handle_security_quality', 'handle_security_sbom', 'handle_security_sign', 'handle_security_sigstore_status', 'handle_security_verify', 'handle_source_generate', 'handle_sync_config', 'handle_sync_export', 'handle_sync_import', 'handle_sync_pull', 'handle_sync_push', 'handle_system_benchmark', 'handle_system_cross_check', 'handle_system_install_pkg', 'handle_system_open_path', 'handle_system_snapshot_install', 'handle_system_snapshot_remove', 'handle_system_snapshot_status', 'handle_system_verify_rollback', 'handle_tools_abi_check', 'handle_tools_attest', 'handle_tools_audit', 'handle_tools_publish', 'handle_tools_rpm_to_deb', 'handle_tools_scan_image', 'handle_tools_snapshot_install', 'handle_tools_snapshot_remove', 'handle_tools_snapshot_status', 'restore_queue', 'serve', 'serve_http']
__all__ += ['handle_app_doctor', 'handle_app_version', 'handle_dbus_status', 'handle_history_list', 'handle_plugin_audit', 'handle_plugin_available', 'handle_plugin_list', 'handle_policy_evaluate', 'handle_policy_get', 'handle_policy_set', 'handle_profile_current', 'handle_profile_list', 'handle_settings_get', 'handle_settings_set', 'handle_stats_wrapped', 'handle_system_health', 'handle_tools_status']
__all__ += ['handlers_pipeline', 'handlers_queue', 'handlers_repo', 'handlers_security', 'handlers_system', 'handlers_tools', 'http', 'protocol', 'registry', 'transport']
