"""PkgForge sidecar API — JSON-RPC method registry (F2.2 split)."""
from __future__ import annotations

from core.api.handlers_pipeline import (
    handle_history_clear,
    handle_history_restore,
    handle_history_rollback,
    handle_history_uninstall,
    handle_pipeline_approve,
    handle_pipeline_cancel,
    handle_pipeline_dismiss,
    handle_pipeline_start,
)
from core.api.handlers_queue import (
    handle_profile_create,
    handle_profile_delete,
    handle_profile_switch,
    handle_queue_add,
    handle_queue_cancel,
    handle_queue_clear,
    handle_queue_list,
    handle_queue_priority,
    handle_queue_remove,
    handle_queue_start,
    handle_schedule_get,
    handle_schedule_run,
    handle_schedule_set,
    handle_schedule_timer_install,
    handle_sync_config,
    handle_sync_export,
    handle_sync_import,
    handle_sync_pull,
    handle_sync_push,
)
from core.api.handlers_repo import (
    handle_aur_build,
    handle_aur_info,
    handle_aur_search,
    handle_compare_diff,
    handle_plugin_install,
    handle_plugin_uninstall,
    handle_plugin_update,
)
from core.api.handlers_security import (
    handle_security_cve_scan,
    handle_security_keys,
    handle_security_provenance,
    handle_security_provenance_create,
    handle_security_quality,
    handle_security_sbom,
    handle_security_sign,
    handle_security_sigstore_status,
    handle_security_verify,
)
from core.api.handlers_system import (
    handle_delta_disable,
    handle_delta_enable,
    handle_delta_status,
    handle_export_appimage_to_deb,
    handle_export_flatpak_list,
    handle_export_flatpak_to_deb,
    handle_export_oci,
    handle_graph_build,
    handle_source_generate,
    handle_system_benchmark,
    handle_system_cross_check,
    handle_system_install_pkg,
    handle_system_open_path,
    handle_system_snapshot_install,
    handle_system_snapshot_remove,
    handle_system_snapshot_status,
    handle_system_verify_rollback,
)
from core.api.handlers_tools import (
    handle_dbus_set_policy,
    handle_dbus_start,
    handle_fleet_status,
    handle_install_rehearse,
    handle_tools_abi_check,
    handle_tools_attest,
    handle_tools_audit,
    handle_tools_publish,
    handle_tools_rpm_to_deb,
    handle_tools_scan_image,
    handle_tools_snapshot_install,
    handle_tools_snapshot_remove,
    handle_tools_snapshot_status,
)
from core.http_api.meta import (
    handle_app_doctor,
    handle_app_version,
    handle_policy_evaluate,
    handle_policy_get,
    handle_policy_set,
    handle_settings_get,
    handle_settings_set,
    handle_stats_wrapped,
    handle_system_health,
    handle_tools_status,
)
from core.http_api.read import (
    handle_dbus_status,
    handle_history_list,
    handle_plugin_audit,
    handle_plugin_available,
    handle_plugin_list,
    handle_profile_current,
    handle_profile_list,
)

METHODS = {
    "app.version": handle_app_version,
    "app.doctor": handle_app_doctor,
    "tools.status": handle_tools_status,
    "settings.get": handle_settings_get,
    "settings.set": handle_settings_set,
    "pipeline.start": handle_pipeline_start,
    "pipeline.cancel": handle_pipeline_cancel,
    "pipeline.approve": handle_pipeline_approve,
    "pipeline.dismiss": handle_pipeline_dismiss,
    "history.list": handle_history_list,
    "history.uninstall": handle_history_uninstall,
    "history.rollback": handle_history_rollback,
    "history.clear": handle_history_clear,
    "history.restore": handle_history_restore,
    # Faz 1 / A2: security panel
    "security.verify": handle_security_verify,
    "security.sign": handle_security_sign,
    "security.keys": handle_security_keys,
    "security.sbom": handle_security_sbom,
    "security.quality": handle_security_quality,
    "security.provenance": handle_security_provenance,
    "security.provenance_create": handle_security_provenance_create,
    "security.sigstore_status": handle_security_sigstore_status,
    "security.cve_scan": handle_security_cve_scan,
    # Faz 1 / A4: delta updater
    "delta.status": handle_delta_status,
    "delta.enable": handle_delta_enable,
    "delta.disable": handle_delta_disable,
    # Faz 1 / A1: export centers
    "export.oci": handle_export_oci,
    "export.appimage_to_deb": handle_export_appimage_to_deb,
    "export.flatpak_list": handle_export_flatpak_list,
    "export.flatpak_to_deb": handle_export_flatpak_to_deb,
    # Faz 1 / A3: dependency graph
    "graph.build": handle_graph_build,
    # Faz 1 / A5: from-source
    "source.generate": handle_source_generate,
    # Faz 1 / A6: system tools
    "system.health": handle_system_health,
    "stats.wrapped": handle_stats_wrapped,
    "policy.evaluate": handle_policy_evaluate,
    "policy.get": handle_policy_get,
    "policy.set": handle_policy_set,
    "system.cross_check": handle_system_cross_check,
    "system.snapshot_status": handle_system_snapshot_status,
    "system.snapshot_install": handle_system_snapshot_install,
    "system.snapshot_remove": handle_system_snapshot_remove,
    "system.open_path": handle_system_open_path,
    "system.install_pkg": handle_system_install_pkg,
    "system.verify_rollback": handle_system_verify_rollback,
    "system.benchmark": handle_system_benchmark,
    "plugin.uninstall": handle_plugin_uninstall,
    "plugin.install": handle_plugin_install,
    "plugin.update": handle_plugin_update,
    "plugin.audit": handle_plugin_audit,
    "plugin.list": handle_plugin_list,
    "plugin.available": handle_plugin_available,
    "compare.diff": handle_compare_diff,
    # Faz 2 / B1: AUR browser
    "aur.search": handle_aur_search,
    "aur.info": handle_aur_info,
    "aur.build": handle_aur_build,
    # Faz 2 / B6: batch conversion queue
    "queue.add": handle_queue_add,
    "queue.list": handle_queue_list,
    "queue.priority": handle_queue_priority,
    "queue.remove": handle_queue_remove,
    "queue.clear": handle_queue_clear,
    "queue.start": handle_queue_start,
    "queue.cancel": handle_queue_cancel,
    # Faz 2 / B3: scheduled tasks
    "schedule.get": handle_schedule_get,
    "schedule.set": handle_schedule_set,
    "profile.list": handle_profile_list,
    "profile.current": handle_profile_current,
    "profile.create": handle_profile_create,
    "profile.switch": handle_profile_switch,
    "profile.delete": handle_profile_delete,
    "sync.export": handle_sync_export,
    "sync.import": handle_sync_import,
    "sync.config": handle_sync_config,
    "schedule.timer_install": handle_schedule_timer_install,
    "schedule.run": handle_schedule_run,
    "sync.push": handle_sync_push,
    "sync.pull": handle_sync_pull,
    "dbus.status": handle_dbus_status,
    "dbus.start": handle_dbus_start,
    "dbus.set_policy": handle_dbus_set_policy,
    "install.rehearse": handle_install_rehearse,
    # Faz 5 / Feature Tezgahi: kalan CLI ozellikleri
    "tools.rpm_to_deb": handle_tools_rpm_to_deb,
    "tools.abi_check": handle_tools_abi_check,
    "tools.audit": handle_tools_audit,
    # Faz 5 / Feature Tezgahi Faz 2: scan-image/attest/publish/snapshot-cleanup
    "tools.scan_image": handle_tools_scan_image,
    "tools.attest": handle_tools_attest,
    "tools.publish": handle_tools_publish,
    "tools.snapshot_status": handle_tools_snapshot_status,
    "tools.snapshot_install": handle_tools_snapshot_install,
    "tools.snapshot_remove": handle_tools_snapshot_remove,
    # Faz 5 / Fleet konsolu (Alan D)
    "fleet.status": handle_fleet_status,
}
