"""PkgForge — AUR Package Auto-Publish.

Generates PKGBUILD + .SRCINFO and pushes to AUR for converted packages.

Usage:
    from core.aur_publish import prepare_aur_package, push_to_aur

    ok, msg = prepare_aur_package(pkg_path, output_dir)
    ok, msg = push_to_aur(aur_repo_url, ssh_key)
"""

from __future__ import annotations

import logging
import shlex
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from config import extract_package_name
from core.security import safe_run
from i18n import tr

log = logging.getLogger(__name__)


@dataclass
class AURPackage:
    """Generated AUR package files."""

    pkgbuild: Path
    srcinfo: Path
    name: str
    version: str


def _extract_pkg_info(pkg_path: Path) -> dict:
    """Extract package name and version from a .pkg.tar.zst file."""
    info: dict[str, str] = {"name": "", "version": ""}

    # Try reading .PKGINFO
    try:
        res = safe_run(
            ["tar", "xf", str(pkg_path), "-O", ".PKGINFO"], timeout=10,
        )
        if res.returncode == 0:
            for line in res.stdout.splitlines():
                if line.startswith("pkgname = "):
                    info["name"] = line.split("=", 1)[1].strip()
                elif line.startswith("pkgver = "):
                    info["version"] = line.split("=", 1)[1].strip()
    except (subprocess.TimeoutExpired, OSError) as exc:
        log.debug(".PKGINFO okunamadi, dosya adindan turetilecek: %s", exc)

    # Fallback: parse filename
    if not info["name"]:
        stem = pkg_path.stem
        # package-1.0.0-1-x86_64.pkg.tar.zst
        parts = stem.split("-")
        if len(parts) >= 4:
            info["version"] = f"{parts[-3]}-{parts[-2]}"
            info["name"] = "-".join(parts[:-3])
        else:
            # Authoritative extraction handles dotted versions and
            # deb/rpm/arch naming; stem.split mis-parses them.
            info["name"] = extract_package_name(pkg_path.name)

    return info


def _generate_srcinfo(pkgbuild_path: Path) -> str:
    """Generate .SRCINFO from PKGBUILD using makepkg --printsrcinfo."""
    res = safe_run(
        ["makepkg", "--printsrcinfo"],
        cwd=str(pkgbuild_path.parent), timeout=30,
    )
    if res.returncode == 0:
        return res.stdout
    return ""


def detect_build_system(repo_dir: Path) -> str:
    """Detect the build system from a repository directory.

    Returns one of: cmake, meson, cargo, autotools, make, python, go, unknown.
    """
    checks = [
        ("CMakeLists.txt", "cmake"),
        ("meson.build", "meson"),
        ("Cargo.toml", "cargo"),
        ("configure.ac", "autotools"),
        ("configure", "autotools"),
        ("Makefile", "make"),
        ("makefile", "make"),
        ("setup.py", "python"),
        ("pyproject.toml", "python"),
        ("go.mod", "go"),
    ]
    for filename, system in checks:
        if (repo_dir / filename).exists():
            return system
    return "unknown"


# Build system → PKGBUILD build/package functions mapping
_BUILD_FUNCTIONS: dict[str, tuple[str, str]] = {
    "cmake": (
        "cmake -B build -DCMAKE_BUILD_TYPE=Release\n    cmake --build build",
        "DESTDIR=\"$pkgdir\" cmake --install build",
    ),
    "meson": (
        "meson setup build\n    meson compile -C build",
        "meson install -C build --destdir \"$pkgdir\"",
    ),
    "cargo": (
        "cargo build --release",
        "install -Dm755 target/release/$pkgname \"$pkgdir/usr/bin/$pkgname\"",
    ),
    "autotools": (
        "./configure --prefix=/usr\n    make",
        "make DESTDIR=\"$pkgdir\" install",
    ),
    "make": (
        "make",
        "make DESTDIR=\"$pkgdir\" install",
    ),
    "python": (
        "python -m build --wheel --no-isolation",
        "python -m installer --destdir=\"$pkgdir\" dist/*.whl",
    ),
    "go": (
        "go build -o $pkgname .",
        "install -Dm755 $pkgname \"$pkgdir/usr/bin/$pkgname\"",
    ),
}


def _generate_pkgbuild(
    name: str,
    version: str,
    git_url: str,
    build_system: str,
) -> str:
    """Generate a PKGBUILD tailored to the detected build system."""
    pkgver = version.split("-")[0] if "-" in version else version
    pkgrel = version.split("-")[1] if "-" in version else "1"

    build_fn, package_fn = _BUILD_FUNCTIONS.get(build_system, _BUILD_FUNCTIONS["make"])

    from core.bash_util import pkgbuild_literal

    source_line = (
        f'"{git_url}/archive/v{pkgver}.tar.gz"' if git_url
        else '"$url"'
    )

    return f"""# Maintainer: PkgForge <noreply@pkgforge.app>
# Contributor: Auto-generated by PkgForge ({build_system})

pkgname={name}
pkgver={pkgver}
pkgrel={pkgrel}
pkgdesc={pkgbuild_literal("Converted from deb/rpm by PkgForge")}
arch=('x86_64')
url={pkgbuild_literal(git_url or "https://aur.archlinux.org")}
license=('GPL-3.0-or-later')
depends=()
makedepends=('{'cmake' if build_system == 'cmake' else 'meson' if build_system == 'meson' else 'cargo' if build_system == 'cargo' else 'python-build python-installer python-setuptools python-wheel' if build_system == 'python' else ''}')
source=({source_line})
sha256sums=('SKIP')

build() {{
    cd "$pkgname-$pkgver" || cd "$srcdir/$pkgname-$pkgver"
    {build_fn}
}}

package() {{
    cd "$pkgname-$pkgver" || cd "$srcdir/$pkgname-$pkgver"
    {package_fn}
}}
"""


def prepare_aur_package(
    pkg_path: Path,
    output_dir: Path,
    git_url: str = "",
    repo_dir: Path | None = None,
) -> tuple[bool, str, AURPackage | None]:
    """Prepare AUR package files from a converted package.

    Args:
        pkg_path: Path to .pkg.tar.zst file.
        output_dir: Directory to write PKGBUILD + .SRCINFO.
        git_url: Git URL for source (used in PKGBUILD source=).
        repo_dir: Optional local repo directory for build system detection.

    Returns:
        (success, message, AURPackage)
    """
    info = _extract_pkg_info(pkg_path)
    name = info.get("name", "") or extract_package_name(pkg_path.name)
    version = info.get("version", "1.0.0")

    # Detect build system from repo directory if provided
    build_system = detect_build_system(repo_dir) if repo_dir else "make"

    # Create AUR repo directory
    aur_dir = output_dir / name
    aur_dir.mkdir(parents=True, exist_ok=True)

    # Generate build-system-aware PKGBUILD
    pkgbuild_content = _generate_pkgbuild(name, version, git_url, build_system)
    pkgbuild_path = aur_dir / "PKGBUILD"
    pkgbuild_path.write_text(pkgbuild_content, encoding="utf-8")

    # Validate PKGBUILD — ensure it's parseable by makepkg
    srcinfo_content = _generate_srcinfo(pkgbuild_path)
    if not srcinfo_content:
        # PKGBUILD validation failed — try simpler fallback
        log.warning("PKGBUILD validation failed, using minimal fallback")
        pkgbuild_content = _generate_pkgbuild(name, version, git_url, "make")
        pkgbuild_path.write_text(pkgbuild_content, encoding="utf-8")
        srcinfo_content = _generate_srcinfo(pkgbuild_path)

    # Generate .SRCINFO
    srcinfo_path = aur_dir / ".SRCINFO"
    if srcinfo_content:
        srcinfo_path.write_text(srcinfo_content, encoding="utf-8")

    aur_pkg = AURPackage(
        pkgbuild=pkgbuild_path,
        srcinfo=srcinfo_path,
        name=name,
        version=version,
    )

    return True, tr("aurpub.aur_paketi_hazir_aur", aur_dir=aur_dir), aur_pkg


def push_to_aur(
    aur_dir: Path,
    aur_repo_url: str,
    ssh_key: str | None = None,
) -> tuple[bool, str]:
    """Push AUR package to AUR via git.

    Args:
        aur_dir: Directory containing PKGBUILD + .SRCINFO.
        aur_repo_url: AUR git clone URL (e.g., ssh://aur@aur.archlinux.org/pkg.git).
        ssh_key: Optional SSH key path.

    Returns:
        (success, message)
    """
    git = shutil.which("git")
    if not git:
        return False, "git bulunamadı"

    # Initialize git repo if needed
    if not (aur_dir / ".git").exists():
        res = safe_run(
            [git, "init", str(aur_dir)], timeout=10,
        )
        if res.returncode != 0:
            return False, tr("aurpub.git_init_basarisiz_stderr", stderr=res.stderr[:200])

    # Configure git user
    safe_run(
        [git, "config", "user.email", "noreply@pkgforge.app"],
        cwd=str(aur_dir), timeout=5,
    )
    safe_run(
        [git, "config", "user.name", "PkgForge"],
        cwd=str(aur_dir), timeout=5,
    )

    # Add remote if not exists
    res = safe_run(
        [git, "remote", "get-url", "origin"],
        cwd=str(aur_dir), timeout=5,
    )
    if res.returncode != 0:
        cmd = [git, "remote", "add", "origin", aur_repo_url]
        if ssh_key:
            cmd = ["git", "-c", f"core.sshCommand=ssh -i {shlex.quote(ssh_key)}"] + cmd[1:]
        safe_run(cmd, cwd=str(aur_dir), timeout=10)

    # Stage and commit
    safe_run(
        [git, "add", "PKGBUILD", ".SRCINFO"],
        cwd=str(aur_dir), timeout=10,
    )
    safe_run(
        [git, "commit", "-m", "Update package"],
        cwd=str(aur_dir), timeout=10,
    )

    # Push
    push_cmd = [git, "push", "origin", "master"]
    if ssh_key:
        push_cmd = ["git", "-c", f"core.sshCommand=ssh -i {shlex.quote(ssh_key)}", "push", "origin", "master"]

    res = safe_run(
        push_cmd,
        cwd=str(aur_dir), timeout=60,
    )

    if res.returncode == 0:
        return True, tr("aurpub.aur_basariyla_yuklendi_aur", aur_repo_url=aur_repo_url)
    else:
        return False, tr("aurpub.push_basarisiz_stderr", stderr=res.stderr[:300])
