"""PkgForge — Automatic Snapshot Cleanup.

Creates and manages a systemd service + timer that automatically cleans
up old Btrfs/ZFS snapshots older than a configurable number of days.

Usage:
    from core.snapshot_cleanup import install_cleanup_service, remove_cleanup_service

    ok, msg = install_cleanup_service(max_age_days=7)
    ok, msg = remove_cleanup_service()
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

from core.privileged import privileged_remove_argv
from core.security import safe_run
from core.snapshot_manager import detect_backend

log = logging.getLogger(__name__)

SERVICE_NAME = "pkgforge-snapshot-cleanup"
TIMER_NAME = "pkgforge-snapshot-cleanup"


def _generate_cleanup_script(max_age_days: int) -> str:
    """Generate the cleanup shell script content."""
    return f"""#!/bin/bash
# PkgForge Automatic Snapshot Cleanup
# Removes PkgForge snapshots older than {max_age_days} days
# Generated by PkgForge — do not edit manually

set -euo pipefail

MAX_AGE_DAYS={max_age_days}
LOG_FILE="/var/log/pkgforge-snapshot-cleanup.log"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

echo "[$TIMESTAMP] Starting snapshot cleanup (max age: $MAX_AGE_DAYS days)" >> "$LOG_FILE" 2>/dev/null || true

CLEANED=0
ERRORS=0

# Detect backend
if command -v btrfs &>/dev/null && btrfs filesystem show / &>/dev/null; then
    BACKEND="btrfs"
elif command -v zfs &>/dev/null; then
    BACKEND="zfs"
else
    echo "[$TIMESTAMP] No snapshot backend found, exiting" >> "$LOG_FILE" 2>/dev/null || true
    exit 0
fi

CUTOFF_EPOCH=$(date -d "-${{MAX_AGE_DAYS}} days" +%s 2>/dev/null || date -v-${{MAX_AGE_DAYS}}d +%s 2>/dev/null || echo 0)

if [ "$CUTOFF_EPOCH" -eq 0 ]; then
    echo "[$TIMESTAMP] Could not calculate cutoff date, exiting" >> "$LOG_FILE" 2>/dev/null || true
    exit 1
fi

if [ "$BACKEND" = "btrfs" ]; then
    # List all pkgforge snapshots
    while IFS= read -r line; do
        SNAP_NAME=$(echo "$line" | awk '{{print $NF}}')
        if [[ "$SNAP_NAME" == pkgforge-* ]]; then
            # Get creation time from btrfs subvolume list
            SNAP_PATH="/$SNAP_NAME"
            # Check if older than cutoff
            if [ -d "$SNAP_PATH" ]; then
                SNAP_MTIME=$(stat -c %Y "$SNAP_PATH" 2>/dev/null || stat -f %m "$SNAP_PATH" 2>/dev/null || echo 0)
                if [ "$SNAP_MTIME" -gt 0 ] && [ "$SNAP_MTIME" -lt "$CUTOFF_EPOCH" ]; then
                    echo "[$TIMESTAMP] Deleting old snapshot: $SNAP_PATH" >> "$LOG_FILE" 2>/dev/null || true
                    if btrfs subvolume delete "$SNAP_PATH" 2>>"$LOG_FILE"; then
                        CLEANED=$((CLEANED + 1))
                    else
                        ERRORS=$((ERRORS + 1))
                    fi
                fi
            fi
        fi
    done < <(btrfs subvolume list / 2>/dev/null)

elif [ "$BACKEND" = "zfs" ]; then
    DATASET=$(zfs list -o name,mountpoint -H -t filesystem 2>/dev/null | awk '$2=="/" {{print $1}}')
    if [ -n "$DATASET" ]; then
        while IFS= read -r snap; do
            if [ -n "$snap" ]; then
                # Get creation time
                CREATION=$(zfs get -H -o value creation "$snap" 2>/dev/null | xargs -I{{}} date -d "{{}}" +%s 2>/dev/null || echo 0)
                if [ "$CREATION" -gt 0 ] && [ "$CREATION" -lt "$CUTOFF_EPOCH" ]; then
                    echo "[$TIMESTAMP] Deleting old snapshot: $snap" >> "$LOG_FILE" 2>/dev/null || true
                    if zfs destroy "$snap" 2>>"$LOG_FILE"; then
                        CLEANED=$((CLEANED + 1))
                    else
                        ERRORS=$((ERRORS + 1))
                    fi
                fi
            fi
        done < <(zfs list -H -t snapshot -o name 2>/dev/null | grep "^${{DATASET}}@pkgforge-")
    fi
fi

echo "[$TIMESTAMP] Cleanup complete: $CLEANED deleted, $ERRORS errors" >> "$LOG_FILE" 2>/dev/null || true
"""


def _generate_service_unit() -> str:
    """Generate the systemd service unit file."""
    return """[Unit]
Description=PkgForge Snapshot Cleanup
After=local-fs.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/pkgforge-snapshot-cleanup.sh
User=root
StandardOutput=journal
StandardError=journal
"""


def _generate_timer_unit(max_age_days: int) -> str:
    """Generate the systemd timer unit file."""
    return f"""[Unit]
Description=PkgForge Snapshot Cleanup Timer (every {max_age_days} days)

[Timer]
OnCalendar=*-*-* 03:00:00
RandomizedDelaySec=3600
Persistent=true

[Install]
WantedBy=timers.target
"""


def install_cleanup_service(max_age_days: int = 7) -> tuple[bool, str]:
    """Install the systemd service and timer for snapshot cleanup.

    Args:
        max_age_days: Delete snapshots older than this many days.

    Returns:
        (success, message)
    """
    backend = detect_backend()
    if backend == "none":
        return False, "Btrfs veya ZFS algılanmadı — snapshot cleanup kurulamıyor"

    # Check if systemd is available
    systemctl = None
    for path in ["/usr/bin/systemctl", "/bin/systemctl", "/usr/sbin/systemctl"]:
        if os.path.isfile(path):
            systemctl = path
            break

    if not systemctl:
        return False, "systemctl bulunamadı — systemd kurulu değil"

    # Generate and write the cleanup script
    script_content = _generate_cleanup_script(max_age_days)
    script_path = Path("/usr/local/bin/pkgforge-snapshot-cleanup.sh")

    # Generate service and timer units
    service_content = _generate_service_unit()
    timer_content = _generate_timer_unit(max_age_days)

    service_path = Path(f"/etc/systemd/system/{SERVICE_NAME}.service")
    timer_path = Path(f"/etc/systemd/system/{TIMER_NAME}.timer")

    # Faz 14: TUM dosyalar TEK pkexec diyaloğunda (write-batch); eski
    # akış 4-5 ayrı diyalog açıyordu.
    try:
        from core.privileged import (
            build_write_batch_manifest,
            privileged_systemctl_argv,
            privileged_write_batch_argv,
        )

        manifest = build_write_batch_manifest([
            ("755", str(script_path), script_content),
            ("644", str(service_path), service_content),
            ("644", str(timer_path), timer_content),
        ])
        res = safe_run(privileged_write_batch_argv("pkexec"),
                       input=manifest, timeout=30)
        if res.returncode != 0:
            return False, f"Dosyalar yazılamadı (kod {res.returncode})"

        # Enable/start: helper uzerinden yetkili systemctl.
        safe_run(privileged_systemctl_argv("pkexec", "daemon-reload"), timeout=15)
        safe_run(privileged_systemctl_argv("pkexec", "enable",
                                           f"{TIMER_NAME}.timer"), timeout=15)
        safe_run(privileged_systemctl_argv("pkexec", "start",
                                           f"{TIMER_NAME}.timer"), timeout=15)

        msg = (
            f"✅ Snapshot cleanup servisi kuruldu!\n\n"
            f"  Timer: Her gün 03:00'da çalışır\n"
            f"  Maksimum snapshot yaşı: {max_age_days} gün\n"
            f"  Servis: {SERVICE_NAME}.service\n"
            f"  Timer: {TIMER_NAME}.timer\n\n"
            f"  Durumu kontrol: systemctl status {TIMER_NAME}.timer\n"
            f"  Kaldır: Raporlar → Temizlik → Kaldır (veya pkgforge snapshot-cleanup --remove)"
        )
        return True, msg

    except Exception as exc:  # noqa: BLE001
        return False, f"Kurulum başarısız: {exc}"


def remove_cleanup_service() -> tuple[bool, str]:
    """Remove the systemd service and timer.

    Returns:
        (success, message)
    """
    systemctl = None
    for path in ["/usr/bin/systemctl", "/bin/systemctl", "/usr/sbin/systemctl"]:
        if os.path.isfile(path):
            systemctl = path
            break

    if not systemctl:
        return False, "systemctl bulunamadı"

    try:
        from core.privileged import privileged_systemctl_argv

        # Faz 14: systemctl fiilleri helper uzerinden yetkili.
        safe_run(privileged_systemctl_argv("pkexec", "stop",
                                           f"{TIMER_NAME}.timer"), timeout=15)
        safe_run(privileged_systemctl_argv("pkexec", "disable",
                                           f"{TIMER_NAME}.timer"), timeout=15)

        # Remove files
        for path in [
            f"/etc/systemd/system/{SERVICE_NAME}.service",
            f"/etc/systemd/system/{TIMER_NAME}.timer",
            "/usr/local/bin/pkgforge-snapshot-cleanup.sh",
        ]:
            p = Path(path)
            if p.exists():
                safe_run(privileged_remove_argv("pkexec", str(p)), timeout=10)

        safe_run(privileged_systemctl_argv("pkexec", "daemon-reload"), timeout=15)

        return True, "✅ Snapshot cleanup servisi kaldırıldı."

    except Exception as exc:  # noqa: BLE001
        return False, f"Kaldırma başarısız: {exc}"


def get_cleanup_status() -> dict:
    """Get current cleanup service status."""
    systemctl = None
    for path in ["/usr/bin/systemctl", "/bin/systemctl", "/usr/sbin/systemctl"]:
        if os.path.isfile(path):
            systemctl = path
            break

    status = {
        "installed": False,
        "active": False,
        "next_run": "",
        "last_run": "",
    }

    if not systemctl:
        return status

    # Check if timer exists
    res = safe_run([systemctl, "is-enabled", f"{TIMER_NAME}.timer"], timeout=5)
    status["installed"] = res.returncode == 0

    if status["installed"]:
        # Check if active
        res = safe_run([systemctl, "is-active", f"{TIMER_NAME}.timer"], timeout=5)
        status["active"] = res.returncode == 0

        # Get next run time
        res = safe_run([systemctl, "show", f"{TIMER_NAME}.timer", "--property=NextElapseUSecRealtime"], timeout=5)
        if res.returncode == 0:
            status["next_run"] = res.stdout.split("=", 1)[1].strip() if "=" in res.stdout else ""

    return status
