#!/usr/bin/env python3
"""Generate desktop/src/lib/api-types.ts from the sidecar METHODS registry.

F5.13: the Python METHODS dict + capabilities reader set are the single
source of truth; this script emits a typed TS mirror so the frontend's
method names stay type-safe. CI re-runs it with --check and fails on
any diff, so a stale generated file can't slip in.

Usage:
    python tools/gen_api_ts.py           # write the file
    python tools/gen_api_ts.py --check   # exit 1 when the file is stale
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

NL = chr(10)
OUT = ROOT / "desktop" / "src" / "lib" / "api-types.ts"

HEADER = """// AUTO-GENERATED by tools/gen_api_ts.py — DO NOT EDIT.
// Source of truth: core/api_server.py METHODS + core/capabilities.py
// Yeniden uret: python tools/gen_api_ts.py
"""


def build_text() -> str:
    from core.api_server import METHODS
    from core.capabilities import http_reader_methods

    methods = sorted(METHODS)
    readers = sorted(http_reader_methods())

    lines: list[str] = [HEADER.rstrip(NL), ""]
    lines.append("export const API_METHODS = [")
    for m in methods:
        lines.append('  "' + m + '",')
    lines.append("] as const;")
    lines.append("")
    lines.append("export type ApiMethod = (typeof API_METHODS)[number];")
    lines.append("")
    lines.append("export const READ_METHODS = [")
    for m in readers:
        lines.append('  "' + m + '",')
    lines.append("] as const;")
    lines.append("")
    lines.append("export type ReadMethod = (typeof READ_METHODS)[number];")
    lines.append("")
    return NL.join(lines)


def main() -> int:
    text = build_text()
    if "--check" in sys.argv:
        existing = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if existing != text:
            print("api-types.ts bayat. Calistirin: python tools/gen_api_ts.py")
            return 1
        print("api-types.ts guncel")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print("yazildi:", OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
